set number
set textwidth=100
set showmatch
set errorbells
set visualbell
set hlsearch
set smartcase
set gdefault
set ignorecase
set incsearch
set autoindent
set expandtab
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4
set ruler
set undolevels=1000
set backspace=indent,eol,start
set cursorline
set mouse=a
set nocompatible

